---
- hosts: localhost
  gather_facts: false
  vars:
    stackname: postgres-backup
  tasks:
    - name: stack for indietools
      cloudformation:
        stack_name: "{{stackname}}"
        state: present
        region: "{{region}}"
        template: postgres-backup.yml
        template_parameters:
          Tag: "{{tag | default('latest')}}"
