---
- hosts: localhost
  gather_facts: false
  vars:
    stackname: postgres-db
    region: us-west-2
  tasks:
    - name: stack for postgres indietools
      cloudformation:
        stack_name: "{{stackname}}"
        state: present
        region: "{{region}}"
        template: postgres-db.yml
        template_parameters:
          Tag: "{{tag | default('latest')}}"
