AWSTemplateFormatVersion: '2010-09-09'
Description: An example service
Parameters:
  Tag:
    Type: String
  Cluster:
    Type: String
    Default: kloudcover
Resources:
  Logs:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub ${AWS::StackName}
      RetentionInDays: 7
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: 1
      TaskDefinition: !Ref Task
      ServiceRegistries:
        - RegistryArn: !GetAtt ServiceDiscovery.Arn
      # HealthCheckGracePeriodSeconds: 120
  ServiceDiscovery:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Description: 'Service discovery for the indietools db'
      DnsConfig:
        DnsRecords:
          - Type: SRV
            TTL: 60
        NamespaceId: ns-5n62syucv3kj72es
      Name: db
  Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      TaskRoleArn: !Ref Role
      Family: postgres
      # NetworkMode: host
      ContainerDefinitions:
        - Name: postgres-db
          Cpu: 100
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/postgres:fg
          MemoryReservation: 300
          # HealthCheck:
          #   Command: ["CMD-SHELL", "pg_isready -U postgres"]
          #   Interval: 5
          #   Timeout: 30
          #   Retries: 3
          Environment:
            - Name: SSM_PATH
              Value: /indietools/staging
            - Name: S3_PREFIX
              Value: indietools/staging
            - Name: S3_BUCKET
              Value: kloudcover
          PortMappings:
            - ContainerPort: 5432
              HostPort: 0
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub ${AWS::StackName}
              awslogs-region: !Sub ${AWS::Region}
              awslogs-stream-prefix: postgres
        - Name: !Sub ${AWS::StackName}-backup
          Cpu: 40
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/postgres:fg
          EntryPoint:
            - ''
          Command:
            - /backup.sh
          Environment:
            - Name: SSM_PATH
              Value: /indietools/staging
            - Name: BACKUP_INTERVAL
              Value: 5d
          MemoryReservation: 200
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub ${AWS::StackName}
              awslogs-region: !Sub ${AWS::Region}
              awslogs-stream-prefix: s3-sync
  Role:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub ${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
          - Effect: "Allow"
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "sts:AssumeRole"
      Path: '/'
      Policies:
        - PolicyName: "ssm_and_s3"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - 's3:*'
                Resource:
                  - 'arn:aws:s3:::kloudcover'
                  - 'arn:aws:s3:::kloudcover/*'
              - Effect: "Allow"
                Action:
                  - 'ssm:Get*'
                Resource:
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/indietools/*"
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ngrok.token"
