AWSTemplateFormatVersion: '2010-09-09'
Description: An example service
Parameters:
  Tag:
    Type: String
  Cluster:
    Type: String
    Default: kloudcover
Resources:
  Logs:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub ${AWS::StackName}
      RetentionInDays: 7
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: 1
      TaskDefinition: !Ref Task
  Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      TaskRoleArn: !Ref Role
      Family: postgres
      NetworkMode: host
      ContainerDefinitions:
        - Name: postgres-db
          Cpu: 100
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/postgres:pg-db
          MemoryReservation: 300
          Environment:
            - Name: SSM_PATH
              Value: /indietools/staging
          PortMappings:
            - ContainerPort: 5432
              HostPort: 5432
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub ${AWS::StackName}
              awslogs-region: !Sub ${AWS::Region}
              awslogs-stream-prefix: postgres
        - Name: !Sub ${AWS::StackName}-backup
          Cpu: 40
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/postgres:pg-db
          EntryPoint:
            - ''
          Command:
            - /backup.sh
          Environment:
            - Name: SSM_PATH
              Value: /indietools/staging
            - Name: BACKUP_INTERVAL
              Value: 5m
          MemoryReservation: 200
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub ${AWS::StackName}
              awslogs-region: !Sub ${AWS::Region}
              awslogs-stream-prefix: s3-sync
  Role:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub ${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
          - Effect: "Allow"
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "sts:AssumeRole"
      Path: '/'
      Policies:
        - PolicyName: "ssm_and_s3"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - 's3:*'
                Resource:
                  - 'arn:aws:s3:::kloudcover'
                  - 'arn:aws:s3:::kloudcover/*'
              - Effect: "Allow"
                Action:
                  - 'ssm:Get*'
                Resource:
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/indietools/*"
